### ISSUE TITLE
sns.distplot  AttributeError: 'Rectangle' object has no property 'normed'

### ISSUE THREAD

**Issue by licj1** [dependable-cps/AdversarialAttackPHM#1]
Thank you for your very kind code, I met an question during my implementation as follows:
AttributeError                            Traceback (most recent call last)
<ipython-input-17-691b3dd65219> in <module>()
----> 1 fig = plot_dist(df)

<ipython-input-16-2892407d2ca2> in plot_dist(df, engine_num)
     17         df_plot = df
     18     for col, ax in zip(cols, axes):
---> 19         ax = sns.distplot(df_plot[col], ax=ax, label=col)
~/anaconda3/lib/python3.6/site-packages/seaborn/distributions.py in distplot(a, bins, hist, kde, rug, fit, hist_kws, kde_kws, rug_kws, fit_kws, color, vertical, norm_hist, axlabel, label, ax)
    216         hist_color = hist_kws.pop("color", color)
    217         ax.hist(a, bins, orientation=orientation,
--> 218                 color=hist_color, **hist_kws)
    219         if hist_color != color:
    220             hist_kws["color"] = hist_color

~/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1541     def inner(ax, *args, data=None, **kwargs):
   1542         if data is None:
-> 1543             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1544 
   1545         bound = new_sig.bind(ax, *args, **kwargs)

~/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py in hist(self, x, bins, range, density, weights, cumulative, bottom, histtype, align, orientation, rwidth, log, color, label, stacked, **kwargs)
   6806             if patch:
   6807                 p = patch[0]
-> 6808                 p.update(kwargs)
   6809                 if lbl is not None:
   6810                     p.set_label(lbl)

~/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py in update(self, props)
   1004 
   1005         with cbook._setattr_cm(self, eventson=False):
-> 1006             ret = [_update_property(self, k, v) for k, v in props.items()]
   1007 
   1008         if len(ret):

~/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py in <listcomp>(.0)
   1004 
   1005         with cbook._setattr_cm(self, eventson=False):
-> 1006             ret = [_update_property(self, k, v) for k, v in props.items()]
   1007 
   1008         if len(ret):

~/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py in _update_property(self, k, v)
   1000                 if not callable(func):
   1001                     raise AttributeError('{!r} object has no property {!r}'
-> 1002                                          .format(type(self).__name__, k))
   1003                 return func(v)
   1004 

AttributeError: 'Rectangle' object has no property 'normed'
I want to know what version of python did you use? And how to solve this bug? Look for your reply, thanks!

**Comment by axndj1993** [comment]
Hello, we are using python version 3.6 and matplotlib 3.0.2. Please check your matplotlib version and update if it is necessary.
